name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Uploading only the build directory as an artifact
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    needs: build_and_deploy
    runs-on: ubuntu-latest

    steps:
      # Downloading only the build directory as an artifact
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StreamGPTCEU'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_538FEB8EFBD640FCB3F4F645AABA28E8 }}
          package: build # Deploying only the build directory
